# Browser to use for testing
browser=chrome
# Website URL to test
url=https://www.practo.com/
# User name for form
name=Mrunmayee
# Organization name for form
organization=Cognizant
# Contact number for form
contactNumber=90876534231
# Email address for form
emailId=xyz@gmail.
# Excel file path for results
excelPath= /src/main/resources/test.xlsx